name: Data Connection Test

on: [push] # This runs every time you push code

jobs:
  test-s3-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install DVC & S3 Support
        run: |
          pip install dvc[s3]

      - name: Pull Data from S3
        # Here we inject the secrets into the environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
        run: |
          dvc pull
          echo "Success! Here is the data we pulled:"
          ls -R data/